name: ekspedisi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  simple_icons: ^14.6.1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  path_provider: ^2.1.5
  open_file: ^3.5.10
  dio: ^5.9.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  device_info_plus: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
 


flutter_launcher_icons:
  android: true
  image_path: "assets/icon/Icon-Apk.png"
  



flutter:
  uses-material-design: true

  assets:
    - assets/images/truck.png
    - assets/images/pegawai.png
    - assets/icon/Icon-Apk.png  

  fonts:
    - family: InriaSans
      fonts:
        - asset: assets/fonts/InriaSans-Regular.ttf
        - asset: assets/fonts/InriaSans-Bold.ttf
          weight: 700